### ISSUE TITLE
why the output file is messy code?

### ISSUE THREAD

**Issue by hfsugar** [chenbjin/RepresentationLearning#1]
When I run your code by command "./word2vec -train data.txt -triplet triplets.txt -output vec.txt -size 200 -window 5 -sample 1e-4 -negative 5 -hs 0 -binary 0 -cbow 1 -iter 3", the content in vec.txt are all messy code. How to fix it. Thanks.

**Comment by hfsugar** [comment]
I have solved. Thank you!

**Comment by chenbjin** [comment]
@hfsugar Nice job, could you described how to solve the problem?
